### ISSUE TITLE
Different treatment of omit.coef / custom.coef.names in 1.36.18 vs 1.36.23

### ISSUE THREAD

**Issue by rmcd1024** [leifeld/texreg#46]
The code below runs correctly with texreg_1.36.18 ("logSigma" is omitted from the output), but with texreg_1.36.23 it generates this error:

```
Error in customnames(m, custom.coef.names) : 
  There are 3 coefficients, but you provided 4 custom names for them.
```
This can be sourced and run under the two versions of texreg.
```
library(texreg)
library(censReg)
df <-  data.frame(y=sample(0:5, replace=TRUE, size=50), x=rnorm(50),
                  z=rnorm(50))
reg <- censReg(y ~ x + z, data=df, left=0, right=10)
reg <- lm(y ~ x + z, data=df)
custom.name <- c('Intercept', 'X', 'Z', 'logSigma')
f <- texreg(reg, custom.coef.names=custom.name,
            omit.coef='logSigma')
print(f)
```

**Comment by aaronshaw** [comment]
Confirming the issue and that the same work-around was effective for me. 

Seems that `texreg()` is handling the call to `omit.coef` before `custom.coef`. This does not seem to be true for other custom parameters (e.g., `override.pvalues` and `override.se`).

**Comment by leifeld** [comment]
I think this was changed in commit df67f0b2148127bddfd39211989d81bb38bb7e53 after pull request https://github.com/leifeld/texreg/pull/30 by @vincentarelbundock. Also possibly related to issue #24.

**Comment by vincentarelbundock** [comment]
This has already fixed in master.

``override.pvalues`` and ``override.se`` take vectors of length equal to the length of the coefficient vector *before* ``omit.coef`` is applied. (this has always been the behavior)

``custom.coef`` takes a vector of names of length equal to the length of the coefficient vector either before or after ``omit.coef`` is applied.

```
> library(devtools)
> install_github('leifeld/texreg')
> library(texreg)
> df <-  data.frame(y=sample(0:5, replace=TRUE, size=50), x=rnorm(50), z=rnorm(50))
> reg <- list()
> reg[[1]] <- censReg(y ~ x + z, data=df, left=0, right=10)
> reg[[2]] <- lm(y ~ x + z, data=df)
> custom.name <- c('Intercept', 'X', 'Z', 'Log Sigma')
> screenreg(reg, custom.coef.names=custom.name, omit.coef='logSigma')

=====================================
                Model 1     Model 2  
-------------------------------------
Intercept         2.41 ***   2.53 ***
                 (0.27)     (0.25)   
X                -0.57      -0.42    
                 (0.34)     (0.30)   
Z                 0.45       0.36    
                 (0.28)     (0.25)   
-------------------------------------
AIC             198.43               
BIC             206.08               
Log Likelihood  -95.21               
Num. obs.        50         50       
Left-censored     7                  
Uncensored       43                  
Right-censored    0                  
R^2                          0.06    
Adj. R^2                     0.03    
RMSE                         1.69    
=====================================
*** p < 0.001, ** p < 0.01, * p < 0.05

```

**Comment by felixhaass** [comment]
I'm still experiencing this issue, even after updating to Master. I do like the new `custom.coef.map` option, though, thanks for that!

**Comment by vincentarelbundock** [comment]
@felixhaass I guess I might not be understanding the problem, then. Does the code I pasted illustrate your use case? If so, does it work on your machine?

**Comment by felixhaass** [comment]
Sorry, my fault. It does indeed work. Shouldn't write `R` code on a Friday night... again, thanks for the `custom.coef.map` function; I was working with Will Lowes workaround for some time, nice to see it integrated. Keep up the great work!

**Comment by vincentarelbundock** [comment]
@leifeld I suppose this can be closed, then.
